### ISSUE TITLE
Why not provide a place to give feedback?

### ISSUE THREAD

**Issue by ortonomy** [kamranahmedse/design-patterns-for-humans#121]
I created an issue giving feedback on your project, and you deleted it (https://github.com/kamranahmedse/design-patterns-for-humans/issues/119) 

Wouldn't it have been prudent to reply and then close the issue? The issue even acquired a few reactions of liking, so I don't believe I'm alone in my opinion.

Why? Is there a channel we can open a dialogue? Or did you just not like the feedback?

**Comment by kamranahmedse** [comment]
Hey @ortonomy - thank you for opening the issue. 

I have got tons of complaints about the repository subscription emails in the past from people considering it to be me spamming them with the back-and-forth communication on the issues for the repositories where I have lots of watchers. I would have probably deleted it during the cleanup phase if I would have found it to be not relevant enough or align with the goals of the project. 

[GitHub discussions](https://help.github.com/en/github/building-a-strong-community/about-team-discussions) will hopefully fix it once we get access to it. I don't remember what the issue was about but feel free to remind me. I apologize if it caused you any inconvenience.
