### ISSUE TITLE
Wrong Decorator Pattern definition

### ISSUE THREAD

**Issue by AdrienTorris** [kamranahmedse/design-patterns-for-humans#80]
Hi. Thank you for this page, the real world examples you found are very good.

I post this issue because I have a doubt about your example for the Decorator pattern. The main feature of this pattern is to be an alternative to inheritance, but in your example your are just implementing inheritance, you are not using any decorator.

Using your coffee situation, a decorator example would seems like this (in C#, sorry) : 

```
public abstract class Coffee
{
	public int Price {get;set;}
	public int Quantity {get;set;}
	
	public Coffee(int price, int quantity)
	{
		Price=price;
		Quantity = quantity;
	}
}

public class MilkCoffee : Coffee
{
}

public class WhipCoffee : Coffee
{
}

public abstract class Decorator : Coffee
{
	protected Coffee coffee;
	
	public Decorator(Coffee c)
	{
		coffee = c;
	}
}

public const int CUP_QUANTITY = 20;

public abstract class OrderableCoffee : Decorator
{
	protected List<string> Customers = new List<string>();
	
	public OrderableCoffee(Coffee coffee)
	  : base(coffee)
	{ }
	
	public void Order(string customerName)
	{
		if(coffee.Quantity < CUP_QUANTITY)
		{
			Console.WriteLine("No more coffee. Sorry.");
			return;
		}
		
		Customers.Add(customerName);
		coffee.Quantity -= CUP_QUANTITY;
		
		Console.WriteLine("Order done.");
	}
}
```

Implementation:

```
MilkCoffee milkCoffee = new MilkCoffee("2", 450);
WhipCoffee whipCoffee = new WhipCoffee("3", 700);

// Make the milk coffee odrerable
OrderableCoffee orderableMilkCoffee = new OrderableCoffee(milkCoffee);
orderableMilkCoffee.Order("Customer #1");
orderableMilkCoffee.Order("Customer #2");
```

**Comment by AdrienTorris** [comment]
Same example with more functionalities : 

```
public abstract class Coffee
{
	public int Price {get;set;}
	public int Quantity {get;set;}
	
	public Coffee(int price, int quantity)
	{
		Price=price;
		Quantity = quantity;
	}
	
	public abstract void Display();
}

public class MilkCoffee : Coffee
{
	public override void Display() => Console.WriteLine($"Milk coffee. Price: {Price}€. Quantity: {Quantity}ml")
}

public class WhipCoffee : Coffee
{
	public override void Display() => Console.WriteLine($"Delicious whip coffee. Price: {Price}€. Quantity: {Quantity}ml")
}

public abstract class Decorator : Coffee
{
	protected Coffee coffee;
	
	public Decorator(Coffee c)
	{
		coffee = c;
	}
	
	public override void Display() => coffee.Display();
}

public const int CUP_QUANTITY = 20;

public abstract class OrderableCoffee : Decorator
{
	protected List<string> Customers = new List<string>();
	
	public OrderableCoffee(Coffee coffee)
	  : base(coffee)
	{ }
	
	public void Order(string customerName)
	{
		if(coffee.Quantity < CUP_QUANTITY)
		{
			Console.WriteLine("No more coffee. Sorry.");
			return;
		}
		
		Customers.Add(customerName);
		coffee.Quantity -= CUP_QUANTITY;
		
		Console.WriteLine("Order done. Coffee quantity has been updated.");
		coffee.Display();
	}
	
	public override void Display()
	{
		base.Display();
		
		if(Customers != null && Customers.Count > 0)
		{
			Console.WriteLine("Customers : ");
			foreach(string customer in Customers)
				Console.WriteLine("----- " + customer);
		}
	}
}
```

Implementation : 

```
MilkCoffee milkCoffee = new MilkCoffee("2", 450);
WhipCoffee whipCoffee = new WhipCoffee("3", 700);

// Make the milk coffee odrerable
OrderableCoffee orderableMilkCoffee = new OrderableCoffee(milkCoffee);
orderableMilkCoffee.Order("Customer #1");
orderableMilkCoffee.Order("Customer #2");

orderableMilkCoffee.Display();
```

**Comment by adie90** [comment]
Kata di dalam ( ..... ) Itu harus di ganti username saya kah??Dikirim dari Ponsel Huawei saya-------- Pesan Asli --------Subjek: Re: [kamranahmedse/design-patterns-for-humans] Wrong decorator definition (#80)Dari: Adrien Torris Kepada: kamranahmedse/design-patterns-for-humans CC: Subscribed Same example with more functionalities :
public abstract class Coffee
{
	public int Price {get;set;}
	public int Quantity {get;set;}
	
	public Coffee(int price, int quantity)
	{
		Price=price;
		Quantity = quantity;
	}
	
	public abstract void Display();
}

public class MilkCoffee : Coffee
{
	public override void Display() => Console.WriteLine($"Milk coffee. Price: {Price}€. Quantity: {Quantity}ml")
}

public class WhipCoffee : Coffee
{
	public override void Display() => Console.WriteLine($"Delicious whip coffee. Price: {Price}€. Quantity: {Quantity}ml")
}

public abstract class Decorator : Coffee
{
	protected Coffee coffee;
	
	public Decorator(Coffee c)
	{
		coffee = c;
	}
	
	public override void Display() => coffee.Display();
}

public const int CUP_QUANTITY = 20;

public abstract class OrderableCoffee : Decorator
{
	protected List<string> Customers = new List<string>();
	
	public OrderableCoffee(Coffee coffee)
	  : base(coffee)
	{ }
	
	public void Order(string customerName)
	{
		if(coffee.Quantity < CUP_QUANTITY)
		{
			Console.WriteLine("No more coffee. Sorry.");
			return;
		}
		
		Customers.Add(customerName);
		coffee.Quantity -= CUP_QUANTITY;
		
		Console.WriteLine("Order done. Coffee quantity has been updated.");
		coffee.Display();
	}
	
	public override void Display()
	{
		base.Display();
		
		if(Customers != null && Customers.Count > 0)
		{
			Console.WriteLine("Customers : ");
			foreach(string customer in Customers)
				Console.WriteLine("----- " + customer);
		}
	}
}

Implementation :
MilkCoffee milkCoffee = new MilkCoffee("2", 450);
WhipCoffee whipCoffee = new WhipCoffee("3", 700);

// Make the milk coffee odrerable
OrderableCoffee orderableMilkCoffee = new OrderableCoffee(milkCoffee);
orderableMilkCoffee.Order("Customer #1");
orderableMilkCoffee.Order("Customer #2");

orderableMilkCoffee.Display();


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kamranahmedse/design-patterns-for-humans","title":"kamranahmedse/design-patterns-for-humans","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kamranahmedse/design-patterns-for-humans"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AdrienTorris in #80: Same example with more functionalities : \r\n\r\n```\r\npublic abstract class Coffee\r\n{\r\n\tpublic int Price {get;set;}\r\n\tpublic int Quantity {get;set;}\r\n\t\r\n\tpublic Coffee(int price, int quantity)\r\n\t{\r\n\t\tPrice=price;\r\n\t\tQuantity = quantity;\r\n\t}\r\n\t\r\n\tpublic abstract void Display();\r\n}\r\n\r\npublic class MilkCoffee : Coffee\r\n{\r\n\tpublic override void Display() =\u003e Console.WriteLine($\"Milk coffee. Price: {Price}€. Quantity: {Quantity}ml\")\r\n}\r\n\r\npublic class WhipCoffee : Coffee\r\n{\r\n\tpublic override void Display() =\u003e Console.WriteLine($\"Delicious whip coffee. Price: {Price}€. Quantity: {Quantity}ml\")\r\n}\r\n\r\npublic abstract class Decorator : Coffee\r\n{\r\n\tprotected Coffee coffee;\r\n\t\r\n\tpublic Decorator(Coffee c)\r\n\t{\r\n\t\tcoffee = c;\r\n\t}\r\n\t\r\n\tpublic override void Display() =\u003e coffee.Display();\r\n}\r\n\r\npublic const int CUP_QUANTITY = 20;\r\n\r\npublic abstract class OrderableCoffee : Decorator\r\n{\r\n\tprotected List\u003cstring\u003e Customers = new List\u003cstring\u003e();\r\n\t\r\n\tpublic OrderableCoffee(Coffee coffee)\r\n\t  : base(coffee)\r\n\t{ }\r\n\t\r\n\tpublic void Order(string customerName)\r\n\t{\r\n\t\tif(coffee.Quantity \u003c CUP_QUANTITY)\r\n\t\t{\r\n\t\t\tConsole.WriteLine(\"No more coffee. Sorry.\");\r\n\t\t\treturn;\r\n\t\t}\r\n\t\t\r\n\t\tCustomers.Add(customerName);\r\n\t\tcoffee.Quantity -= CUP_QUANTITY;\r\n\t\t\r\n\t\tConsole.WriteLine(\"Order done. Coffee quantity has been updated.\");\r\n\t\tcoffee.Display();\r\n\t}\r\n\t\r\n\tpublic override void Display()\r\n\t{\r\n\t\tbase.Display();\r\n\t\t\r\n\t\tif(Customers != null \u0026\u0026 Customers.Count \u003e 0)\r\n\t\t{\r\n\t\t\tConsole.WriteLine(\"Customers : \");\r\n\t\t\tforeach(string customer in Customers)\r\n\t\t\t\tConsole.WriteLine(\"----- \" + customer);\r\n\t\t}\r\n\t}\r\n}\r\n```\r\n\r\nImplementation : \r\n\r\n```\r\nMilkCoffee milkCoffee = new MilkCoffee(\"2\", 450);\r\nWhipCoffee whipCoffee = new WhipCoffee(\"3\", 700);\r\n\r\n// Make the milk coffee odrerable\r\nOrderableCoffee orderableMilkCoffee = new OrderableCoffee(milkCoffee);\r\norderableMilkCoffee.Order(\"Customer #1\");\r\norderableMilkCoffee.Order(\"Customer #2\");\r\n\r\norderableMilkCoffee.Display();\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/kamranahmedse/design-patterns-for-humans/issues/80#issuecomment-285636948"}}}

**Comment by kamranahmedse** [comment]
Hi @AdrienTorris thank you for reporting but it is fine. It is not about the inheritance, I could have made the `Coffee` an interface and it still would have worked. I just made it abstract class to share the setters. 

According to definition:

> Decorator pattern lets you dynamically change the behavior of an object at run time by wrapping them in an object of a decorator class

We create any coffee and at any point of time it is a valid coffee. We keep decorating it (adding Milk, Vanilla etc) to modify it dynamically as per our needs.
